on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: wget -O lilypond.tar.gz https://gitlab.com/lilypond/lilypond/-/releases/v2.24.2/downloads/lilypond-2.24.2-linux-x86_64.tar.gz
      - run: tar xzf lilypond.tar.gz
      - run: ./lilypond-2.24.2/bin/lilypond -I openlilylib -dno-point-and-click medley.ly
      - uses: actions/upload-artifact@v3
        with:
          name: Lilypond Output
          path: |
            medley.pdf
            medley.midi
      - name: Upload to Netlify
        # You may pin to the exact commit or the version.
        # uses: MrFlynn/upload-to-netlify-action@9728d607b0282b7ed2e47067e1291d1918ea552b
        uses: MrFlynn/upload-to-netlify-action@v3
        with:
         # File in the repository to upload.
         source-file: medley.midi
         # Target path on the Netlify site to upload the file.
         destination-path: files/medley.midi
         # Name of the site to upload the file to.
         site-name: noaether-cdn
         # Token used for API access to your Netlify account.
         netlify-token: ${{ secrets.NETLIFY_TOKEN }}
      - name: Upload to Netlify
        # You may pin to the exact commit or the version.
        # uses: MrFlynn/upload-to-netlify-action@9728d607b0282b7ed2e47067e1291d1918ea552b
        uses: MrFlynn/upload-to-netlify-action@v3
        with:
         # File in the repository to upload.
         source-file: medley.pdf
         # Target path on the Netlify site to upload the file.
         destination-path: files/medley.pdf
         # Name of the site to upload the file to.
         site-name: noaether-cdn
         # Token used for API access to your Netlify account.
         netlify-token: ${{ secrets.NETLIFY_TOKEN }}
