on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install GhostScript
        run: sudo apt-get -y install ghostscript
      - name: Install Lilypond
        run: wget -O lilypond.tar.gz https://gitlab.com/lilypond/lilypond/-/releases/v2.24.2/downloads/lilypond-2.24.2-linux-x86_64.tar.gz
      - name: Uncompress received data
        run: tar xzf lilypond.tar.gz
      - name: Run the thing
        run: ./lilypond-2.24.2/bin/lilypond -I openlilylib -dno-point-and-click medley.ly
      - name: Save and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lilypond Output
          path: |
            *.pdf
            *.midi
      - name: Compress PDFs
        run: gs -q -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=FullScore.pdf *.pdf
      - name: Upload to Netlify
        # You may pin to the exact commit or the version.
        # uses: MrFlynn/upload-to-netlify-action@9728d607b0282b7ed2e47067e1291d1918ea552b
        uses: MrFlynn/upload-to-netlify-action@v3
        with:
         # File in the repository to upload.
         source-file: |
           FullScore.pdf
           ChefScore.pdf
           ChefScore.midi
         # Target path on the Netlify site to upload the file.
         destination-path: |
           files/FullScore.pdf
           files/ChefScore.pdf
           files/ChefScore.midi
         # Name of the site to upload the file to.
         site-name: noaether-cdn
         # Token used for API access to your Netlify account.
         netlify-token: ${{ secrets.NETLIFY_TOKEN }}
